services:
  - type: web
    name: django-shop
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn shop.wsgi"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: shop-db
          property: connectionString

databases:
  - name: shop-db
    plan: free
