services:
  - type: web
    name: django-shop
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      python manage.py createsuperuser --noinput || true
    startCommand: gunicorn shop.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: shop-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: CLOUDINARY_URL
        value: CLOUDINARY_URL=cloudinary://396642516151933:15b4GFYHqvjli-CRYE-M0lEEzEI@dziqybsic

databases:
  - name: shop-db
    plan: free
    region: frankfurt
